begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(37);
insert into auth.users(id,email,is_anonymous,raw_user_meta_data) values ('50000000-0000-4000-8000-000000000001','engine-test@example.invalid',false,'{}');
insert into auth.sessions(id,user_id) values ('50000000-0000-4000-8000-000000000002','50000000-0000-4000-8000-000000000001');
create temporary table engine_test(k text primary key,v jsonb);grant all on engine_test to authenticated;
set local role anon;
select throws_ok($$select public.bivia_engine_v1('list')$$,'42501',null,'Anonymous engine access denied');
reset role;
select set_config('request.jwt.claims','{"sub":"50000000-0000-4000-8000-000000000001","session_id":"50000000-0000-4000-8000-000000000002"}',true);
set local role authenticated;
select throws_ok($$select public.bivia_engine_v1('list')$$,'42501',null,'Nonadmin denied');
select throws_ok($$select * from private.engine_runs$$,'42501',null,'Direct run access denied');
reset role;
insert into private.admins(user_id) values ('50000000-0000-4000-8000-000000000001');
set local role authenticated;
select lives_ok($$select public.bivia_engine_v1('list')$$,'Admin can list');
select throws_ok($$select public.bivia_engine_v1('create','{"requestId":"50000000-0000-4000-8000-000000000003","brief":{"translation":"NIV"}}')$$,'P0001','Invalid generation brief','Malformed brief rejected');
insert into engine_test values('run',public.bivia_engine_v1('create','{"requestId":"50000000-0000-4000-8000-000000000003","brief":{"kind":"category","categoryIds":["science"],"count":3,"difficulty":"easy","translation":"NIV","sourceMode":"references","notes":""}}'));
select is((select v->>'status' from engine_test where k='run'),'queued','Run queued without spend');
select is((select v->'config'->>'maxToolCalls' from engine_test where k='run'),'16','New runs snapshot sixteen evidence tool calls');
select is((select v->'config'->>'runBudgetUsd' from engine_test where k='run'),'10','Per-run budget remains ten dollars');
select is((select v->'config'->>'workspaceDailyBudgetUsd' from engine_test where k='run'),'30','Workspace daily budget remains thirty dollars');
select is(public.bivia_engine_v1('create','{"requestId":"50000000-0000-4000-8000-000000000003","brief":{"kind":"category","categoryIds":["science"],"count":3,"difficulty":"easy","translation":"NIV","sourceMode":"references","notes":""}}')->>'id',(select v->>'id' from engine_test where k='run'),'Create idempotent');
select ok(jsonb_array_length((select v->'state'->'editorialContext'->'recentQuestions' from engine_test where k='run'))>0,'Editorial history hydrated');
select throws_ok($$select public.bivia_engine_v1('export_draft',jsonb_build_object('id',(select v->>'id' from engine_test where k='run')))$$,'P0001',null,'Incomplete export denied');
select throws_ok($$select private.engine_claim(gen_random_uuid(),0,auth.uid(),'x')$$,'42501',null,'Clients cannot claim provider calls');
reset role;
insert into engine_test values('lease',private.engine_claim((select (v->>'id')::uuid from engine_test where k='run'),0,'50000000-0000-4000-8000-000000000001','50000000-0000-4000-8000-000000000002'));
select throws_ok($$select private.engine_claim((select (v->>'id')::uuid from engine_test where k='run'),0,'50000000-0000-4000-8000-000000000001','50000000-0000-4000-8000-000000000002')$$,'P0001',null,'Duplicate stage claim denied');
insert into engine_test values('call',private.engine_reserve((select (v->>'id')::uuid from engine_test where k='run'),(select (v->>'leaseToken')::uuid from engine_test where k='lease'),'50000000-0000-4000-8000-000000000001','50000000-0000-4000-8000-000000000002','{"stage":"plan"}',100,false));
select ok((select (v->>'reservedCostUsd')::numeric>0 from engine_test where k='call'),'Cost reserved before dispatch');
select throws_ok($$select private.engine_reserve((select (v->>'id')::uuid from engine_test where k='run'),(select (v->>'leaseToken')::uuid from engine_test where k='lease'),'50000000-0000-4000-8000-000000000001','50000000-0000-4000-8000-000000000002','{}',100,false)$$,'P0001',null,'Only one call per lease');
update private.engine_runs set lease_expires_at=now()-interval '1 second' where id=(select (v->>'id')::uuid from engine_test where k='run');
select private.engine_expire((select (v->>'id')::uuid from engine_test where k='run'));
select is((select status from private.engine_runs where id=(select (v->>'id')::uuid from engine_test where k='run')),'uncertain','Expired dispatched call requires explicit recovery');
set local role authenticated;
select throws_ok($$select public.bivia_engine_v1('resolve_uncertain',jsonb_build_object('id',(select v->>'id' from engine_test where k='run'),'reason','Try again'))$$,'P0001',null,'Unknown cost cannot silently retry');
select is(public.bivia_engine_v1('resolve_uncertain',jsonb_build_object('id',(select v->>'id' from engine_test where k='run'),'reason','Accept possible duplicate cost','acknowledgePotentialDuplicateCost',true))->>'status','queued','Explicit recovery queued');
reset role;
select ok((select estimated_cost_usd is null and reserved_cost_usd>0 from private.engine_calls where id=(select (v->>'callId')::uuid from engine_test where k='call')),'Uncertain cost reservation retained');
-- Reserve guards operate before any provider dispatch.
insert into engine_test values('lease2',private.engine_claim((select (v->>'id')::uuid from engine_test where k='run'),(select version from private.engine_runs where id=(select (v->>'id')::uuid from engine_test where k='run')),'50000000-0000-4000-8000-000000000001','50000000-0000-4000-8000-000000000002'));
update private.engine_runs set config=config||'{"runBudgetUsd":0}'::jsonb where id=(select (v->>'id')::uuid from engine_test where k='run');
select throws_ok($$select private.engine_reserve((select (v->>'id')::uuid from engine_test where k='run'),(select (v->>'leaseToken')::uuid from engine_test where k='lease2'),'50000000-0000-4000-8000-000000000001','50000000-0000-4000-8000-000000000002','{}',100,false)$$,'P0001','Run budget would be exceeded by this call reservation','Run budget guard blocks dispatch');
update private.engine_runs set config=config||'{"runBudgetUsd":10,"maxCallsPerRun":1}'::jsonb where id=(select (v->>'id')::uuid from engine_test where k='run');
select throws_ok($$select private.engine_reserve((select (v->>'id')::uuid from engine_test where k='run'),(select (v->>'leaseToken')::uuid from engine_test where k='lease2'),'50000000-0000-4000-8000-000000000001','50000000-0000-4000-8000-000000000002','{}',100,false)$$,'P0001','Run call limit reached','Call ceiling blocks dispatch');
set local role authenticated;
select throws_ok($$select public.bivia_engine_v1('passage_save','{"translation":"NIV","reference":"Fixture","text":"Editor text","rightsAttested":true,"aiUseAttested":false,"rightsNote":"Fixture permission"}')$$,'P0001','Document explicit AI processing rights before attesting permission','General rights do not imply AI-processing rights');
reset role;
-- A provider ID survives worker expiry; resuming polls the same paid call.
update private.engine_calls set status='reserved',lease_token=(select (v->>'leaseToken')::uuid from engine_test where k='lease2') where id=(select (v->>'callId')::uuid from engine_test where k='call');
update private.engine_runs set active_call_id=(select (v->>'callId')::uuid from engine_test where k='call') where id=(select (v->>'id')::uuid from engine_test where k='run');
select private.engine_provider_save((select (v->>'id')::uuid from engine_test where k='run'),(select (v->>'leaseToken')::uuid from engine_test where k='lease2'),(select (v->>'callId')::uuid from engine_test where k='call'),'{"id":"resp_synthetic","status":"in_progress"}'::jsonb);
select is(private.engine_release_pending((select (v->>'id')::uuid from engine_test where k='run'),(select (v->>'leaseToken')::uuid from engine_test where k='lease2'))->>'status','running','Pending background response remains running');
insert into engine_test values('poll',private.engine_claim((select (v->>'id')::uuid from engine_test where k='run'),(select version from private.engine_runs where id=(select (v->>'id')::uuid from engine_test where k='run')),'50000000-0000-4000-8000-000000000001','50000000-0000-4000-8000-000000000002'));
select is((select v->'activeCall'->>'provider_response_id' from engine_test where k='poll'),'resp_synthetic','Resume retrieves saved provider identity');
select throws_ok($$select private.engine_provider_save((select (v->>'id')::uuid from engine_test where k='run'),(select (v->>'leaseToken')::uuid from engine_test where k='poll'),(select (v->>'callId')::uuid from engine_test where k='call'),' {"id":"resp_other","status":"completed"}')$$,'P0001','Provider response identity changed','Cannot replace saved response identity');
update private.engine_runs set lease_expires_at=now()-interval '1 second' where id=(select (v->>'id')::uuid from engine_test where k='run');
select private.engine_expire((select (v->>'id')::uuid from engine_test where k='run'));
select is((select status from private.engine_runs where id=(select (v->>'id')::uuid from engine_test where k='run')),'running','Expired poll lease is resumable without uncertainty');
insert into engine_test values('poll2',private.engine_claim((select (v->>'id')::uuid from engine_test where k='run'),(select version from private.engine_runs where id=(select (v->>'id')::uuid from engine_test where k='run')),'50000000-0000-4000-8000-000000000001','50000000-0000-4000-8000-000000000002'));
select private.engine_provider_save((select (v->>'id')::uuid from engine_test where k='run'),(select (v->>'leaseToken')::uuid from engine_test where k='poll2'),(select (v->>'callId')::uuid from engine_test where k='call'),'{"id":"resp_synthetic","status":"completed","output":[],"usage":{"input_tokens":10,"output_tokens":20}}');
select ok((select provider_result->>'status'='completed' from private.engine_calls where id=(select (v->>'callId')::uuid from engine_test where k='call')),'Terminal raw response persists before stage replay');
select is((select count(*)::int from private.engine_calls where run_id=(select (v->>'id')::uuid from engine_test where k='run')),1,'Poll/resume never reserves a second generation');
-- Provider uncertainty is authoritative even when the caller's boolean is false.
update private.engine_calls set status='uncertain' where id=(select (v->>'callId')::uuid from engine_test where k='call');
select is(private.engine_finish((select (v->>'id')::uuid from engine_test where k='run'),(select (v->>'leaseToken')::uuid from engine_test where k='poll2'),'50000000-0000-4000-8000-000000000001','50000000-0000-4000-8000-000000000002',(select v->'state' from engine_test where k='run'),'Provider HTTP 503 or missing usage',false)->>'status','uncertain','Recorded uncertain outcome cannot downgrade to failed');
set local role authenticated;
select throws_ok($$select public.bivia_engine_v1('retry_stage',jsonb_build_object('id',(select v->>'id' from engine_test where k='run'),'reason','Try again'))$$,'P0001','Only a known failed stage can be retried with an editor reason','Known-failure retry cannot bypass uncertain-cost acknowledgment');
reset role;
-- Synthetic server state tests export authorization without a provider call.
update private.engine_runs set status='review',state=state||jsonb_build_object('nextStage',null,'status','ready','candidates',(select jsonb_agg(jsonb_build_object('id','candidate-'||i,'revision',0,'categoryId','science','prompt','Fixture question '||i,'answers',jsonb_build_array('Alpha','Beta','Gamma','Delta'),'correctIndex',0,'hint','An original contextual clue','reference','Genesis 1:1','connectionExplanation','Fixture explanation')) from generate_series(1,3)i),'reviews',(select jsonb_object_agg('candidate-'||i,jsonb_build_object('accuracy',jsonb_build_object('verdict','pass'),'theology',jsonb_build_object('verdict','pass'),'clues',jsonb_build_object('verdict','pass'),'playtest',jsonb_build_object('answerIndex',0,'ambiguous',false))) from generate_series(1,3)i),'assembly',jsonb_build_object('shortfall',0,'selectedIds',jsonb_build_array('candidate-1','candidate-2','candidate-3'))) where id=(select (v->>'id')::uuid from engine_test where k='run');
set local role authenticated;
select throws_ok($$select public.bivia_engine_v1('export_draft',jsonb_build_object('id',(select v->>'id' from engine_test where k='run')))$$,'P0001',null,'Passing round still requires human approval');
select public.bivia_engine_v1('decide',jsonb_build_object('id',(select v->>'id' from engine_test where k='run'),'candidateId','candidate-'||i,'revision',0,'decision','approved','reason','Reviewed synthetic fixture')) is not null from generate_series(1,3)i;
insert into engine_test values('export',public.bivia_engine_v1('export_draft',jsonb_build_object('id',(select v->>'id' from engine_test where k='run'))));
select is(public.bivia_engine_v1('export_draft',jsonb_build_object('id',(select v->>'id' from engine_test where k='run')))->>'quizId',(select v->>'quizId' from engine_test where k='export'),'Export retry returns the same draft');
reset role;
select is((select status from public.quizzes where id=(select (v->>'quizId')::uuid from engine_test where k='export')),'draft','Export never publishes');
select is((select count(*)::int from private.questions where quiz_id=(select (v->>'quizId')::uuid from engine_test where k='export')),3,'Export preserves complete assembled count');
select ok((select bool_and(hint_reference like '% · Original clue (not a Bible quotation)') from private.questions where quiz_id=(select (v->>'quizId')::uuid from engine_test where k='export')),'Original clues never mislabel NIV quotations');
delete from auth.sessions where id='50000000-0000-4000-8000-000000000002';
set local role authenticated;
select throws_ok($$select public.bivia_engine_v1('list')$$,'42501',null,'Revoked live session denied');
reset role;
select * from finish();rollback;
