-- Correct known seed paraphrases only; do not alter verified authored scripture.
update private.questions q set hint_reference=q.hint_reference || ' · Original clue (not a Bible quotation)' from (values ('Think of a land far toward the rising sun.','Psalm 113:3'),
('The sea is vast and filled with living things.','Psalm 104:25'),
('Paul longed to visit the believers in this city.','Romans 1:15'),
('A baby in a basket was placed among the reeds along this river.','Exodus 2:3'),
('Consider a place of snow and storehouses of hail.','Job 38:22'),
('Sweetness from the honeycomb brings delight.','Proverbs 16:24'),
('Look up and consider the work of the heavens.','Psalm 19:1'),
('Green plants were given a place upon the earth.','Genesis 1:11'),
('The waters become hard as stone in the cold.','Job 38:30'),
('Observe the ant and learn from its ways.','Proverbs 6:6'),
('The vine bears this familiar fruit.','John 15:5'),
('A little of this works through a whole batch of dough.','Matthew 13:33'),
('This tree and its fruit appear in a promise of abundance.','Deuteronomy 8:8'),
('Daniel asked for a meal of vegetables and water.','Daniel 1:12'),
('This fragrant spice was part of a special anointing oil.','Exodus 30:23')) as seed(hint,reference) where q.hint=seed.hint and q.hint_reference=seed.reference;
update private.attempt_questions q set hint_reference=q.hint_reference || ' · Original clue (not a Bible quotation)' from (values ('Think of a land far toward the rising sun.','Psalm 113:3'),
('The sea is vast and filled with living things.','Psalm 104:25'),
('Paul longed to visit the believers in this city.','Romans 1:15'),
('A baby in a basket was placed among the reeds along this river.','Exodus 2:3'),
('Consider a place of snow and storehouses of hail.','Job 38:22'),
('Sweetness from the honeycomb brings delight.','Proverbs 16:24'),
('Look up and consider the work of the heavens.','Psalm 19:1'),
('Green plants were given a place upon the earth.','Genesis 1:11'),
('The waters become hard as stone in the cold.','Job 38:30'),
('Observe the ant and learn from its ways.','Proverbs 6:6'),
('The vine bears this familiar fruit.','John 15:5'),
('A little of this works through a whole batch of dough.','Matthew 13:33'),
('This tree and its fruit appear in a promise of abundance.','Deuteronomy 8:8'),
('Daniel asked for a meal of vegetables and water.','Daniel 1:12'),
('This fragrant spice was part of a special anointing oil.','Exodus 30:23')) as seed(hint,reference) where q.hint=seed.hint and q.hint_reference=seed.reference;
